// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(tla_coreFFI)
import tla_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_tla_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_tla_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * Result of parsing a document
 */
public protocol ParseResultProtocol : AnyObject {
    
    /**
     * Get parse diagnostics (errors, warnings)
     */
    func getDiagnostics()  -> [Diagnostic]
    
    /**
     * Check if parsing succeeded
     */
    func isValid()  -> Bool
    
}

/**
 * Result of parsing a document
 */
open class ParseResult:
    ParseResultProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_tla_core_fn_clone_parseresult(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_tla_core_fn_free_parseresult(pointer, $0) }
    }

    

    
    /**
     * Get parse diagnostics (errors, warnings)
     */
open func getDiagnostics() -> [Diagnostic] {
    return try!  FfiConverterSequenceTypeDiagnostic.lift(try! rustCall() {
    uniffi_tla_core_fn_method_parseresult_get_diagnostics(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Check if parsing succeeded
     */
open func isValid() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_tla_core_fn_method_parseresult_is_valid(self.uniffiClonePointer(),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeParseResult: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = ParseResult

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> ParseResult {
        return ParseResult(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: ParseResult) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ParseResult {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: ParseResult, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeParseResult_lift(_ pointer: UnsafeMutableRawPointer) throws -> ParseResult {
    return try FfiConverterTypeParseResult.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeParseResult_lower(_ value: ParseResult) -> UnsafeMutableRawPointer {
    return FfiConverterTypeParseResult.lower(value)
}




/**
 * Main TLA+ language services interface
 */
public protocol TlaCoreProtocol : AnyObject {
    
    /**
     * Analyze the context at a given position in the source code.
     * Returns the completion context to determine what completions are appropriate.
     */
    func analyzeContext(result: ParseResult, position: Position)  -> CompletionContext
    
    /**
     * Get completions at a position.
     * Uses cached keyword completions for performance.
     */
    func getCompletions(result: ParseResult, position: Position)  -> [CompletionItem]
    
    /**
     * Get detailed completions based on context at position.
     */
    func getDetailedCompletions(result: ParseResult, position: Position)  -> [DetailedCompletionItem]
    
    /**
     * Get syntax highlights for a range.
     * Uses a reusable QueryCursor and pre-interned capture names for performance.
     */
    func getHighlights(result: ParseResult, range: Range)  -> [HighlightToken]
    
    /**
     * Get signature help for an operator call at the given position.
     */
    func getSignatureHelp(result: ParseResult, position: Position)  -> SignatureHelp?
    
    /**
     * Get symbols from parse result
     */
    func getSymbols(result: ParseResult)  -> [Symbol]
    
    /**
     * Parse a TLA+ document
     */
    func parse(source: String) throws  -> ParseResult
    
    /**
     * Parse a TLA+ document incrementally using previous parse result and edit information.
     * This is significantly faster than full parsing for small edits in large documents.
     * Note: The old_result remains valid and usable after this call.
     */
    func parseIncremental(source: String, oldResult: ParseResult, edit: EditInfo) throws  -> ParseResult
    
}

/**
 * Main TLA+ language services interface
 */
open class TlaCore:
    TlaCoreProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_tla_core_fn_clone_tlacore(self.pointer, $0) }
    }
    /**
     * Create a new TLACore instance
     */
public convenience init()throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeParseError.lift) {
    uniffi_tla_core_fn_constructor_tlacore_new($0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_tla_core_fn_free_tlacore(pointer, $0) }
    }

    

    
    /**
     * Analyze the context at a given position in the source code.
     * Returns the completion context to determine what completions are appropriate.
     */
open func analyzeContext(result: ParseResult, position: Position) -> CompletionContext {
    return try!  FfiConverterTypeCompletionContext.lift(try! rustCall() {
    uniffi_tla_core_fn_method_tlacore_analyze_context(self.uniffiClonePointer(),
        FfiConverterTypeParseResult.lower(result),
        FfiConverterTypePosition.lower(position),$0
    )
})
}
    
    /**
     * Get completions at a position.
     * Uses cached keyword completions for performance.
     */
open func getCompletions(result: ParseResult, position: Position) -> [CompletionItem] {
    return try!  FfiConverterSequenceTypeCompletionItem.lift(try! rustCall() {
    uniffi_tla_core_fn_method_tlacore_get_completions(self.uniffiClonePointer(),
        FfiConverterTypeParseResult.lower(result),
        FfiConverterTypePosition.lower(position),$0
    )
})
}
    
    /**
     * Get detailed completions based on context at position.
     */
open func getDetailedCompletions(result: ParseResult, position: Position) -> [DetailedCompletionItem] {
    return try!  FfiConverterSequenceTypeDetailedCompletionItem.lift(try! rustCall() {
    uniffi_tla_core_fn_method_tlacore_get_detailed_completions(self.uniffiClonePointer(),
        FfiConverterTypeParseResult.lower(result),
        FfiConverterTypePosition.lower(position),$0
    )
})
}
    
    /**
     * Get syntax highlights for a range.
     * Uses a reusable QueryCursor and pre-interned capture names for performance.
     */
open func getHighlights(result: ParseResult, range: Range) -> [HighlightToken] {
    return try!  FfiConverterSequenceTypeHighlightToken.lift(try! rustCall() {
    uniffi_tla_core_fn_method_tlacore_get_highlights(self.uniffiClonePointer(),
        FfiConverterTypeParseResult.lower(result),
        FfiConverterTypeRange.lower(range),$0
    )
})
}
    
    /**
     * Get signature help for an operator call at the given position.
     */
open func getSignatureHelp(result: ParseResult, position: Position) -> SignatureHelp? {
    return try!  FfiConverterOptionTypeSignatureHelp.lift(try! rustCall() {
    uniffi_tla_core_fn_method_tlacore_get_signature_help(self.uniffiClonePointer(),
        FfiConverterTypeParseResult.lower(result),
        FfiConverterTypePosition.lower(position),$0
    )
})
}
    
    /**
     * Get symbols from parse result
     */
open func getSymbols(result: ParseResult) -> [Symbol] {
    return try!  FfiConverterSequenceTypeSymbol.lift(try! rustCall() {
    uniffi_tla_core_fn_method_tlacore_get_symbols(self.uniffiClonePointer(),
        FfiConverterTypeParseResult.lower(result),$0
    )
})
}
    
    /**
     * Parse a TLA+ document
     */
open func parse(source: String)throws  -> ParseResult {
    return try  FfiConverterTypeParseResult.lift(try rustCallWithError(FfiConverterTypeParseError.lift) {
    uniffi_tla_core_fn_method_tlacore_parse(self.uniffiClonePointer(),
        FfiConverterString.lower(source),$0
    )
})
}
    
    /**
     * Parse a TLA+ document incrementally using previous parse result and edit information.
     * This is significantly faster than full parsing for small edits in large documents.
     * Note: The old_result remains valid and usable after this call.
     */
open func parseIncremental(source: String, oldResult: ParseResult, edit: EditInfo)throws  -> ParseResult {
    return try  FfiConverterTypeParseResult.lift(try rustCallWithError(FfiConverterTypeParseError.lift) {
    uniffi_tla_core_fn_method_tlacore_parse_incremental(self.uniffiClonePointer(),
        FfiConverterString.lower(source),
        FfiConverterTypeParseResult.lower(oldResult),
        FfiConverterTypeEditInfo.lower(edit),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTLACore: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = TlaCore

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> TlaCore {
        return TlaCore(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: TlaCore) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TlaCore {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: TlaCore, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTLACore_lift(_ pointer: UnsafeMutableRawPointer) throws -> TlaCore {
    return try FfiConverterTypeTLACore.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTLACore_lower(_ value: TlaCore) -> UnsafeMutableRawPointer {
    return FfiConverterTypeTLACore.lower(value)
}


/**
 * A completion suggestion
 */
public struct CompletionItem {
    public var label: String
    public var kind: CompletionKind
    public var detail: String?
    public var insertText: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(label: String, kind: CompletionKind, detail: String?, insertText: String?) {
        self.label = label
        self.kind = kind
        self.detail = detail
        self.insertText = insertText
    }
}



extension CompletionItem: Equatable, Hashable {
    public static func ==(lhs: CompletionItem, rhs: CompletionItem) -> Bool {
        if lhs.label != rhs.label {
            return false
        }
        if lhs.kind != rhs.kind {
            return false
        }
        if lhs.detail != rhs.detail {
            return false
        }
        if lhs.insertText != rhs.insertText {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(label)
        hasher.combine(kind)
        hasher.combine(detail)
        hasher.combine(insertText)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCompletionItem: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CompletionItem {
        return
            try CompletionItem(
                label: FfiConverterString.read(from: &buf), 
                kind: FfiConverterTypeCompletionKind.read(from: &buf), 
                detail: FfiConverterOptionString.read(from: &buf), 
                insertText: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: CompletionItem, into buf: inout [UInt8]) {
        FfiConverterString.write(value.label, into: &buf)
        FfiConverterTypeCompletionKind.write(value.kind, into: &buf)
        FfiConverterOptionString.write(value.detail, into: &buf)
        FfiConverterOptionString.write(value.insertText, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompletionItem_lift(_ buf: RustBuffer) throws -> CompletionItem {
    return try FfiConverterTypeCompletionItem.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompletionItem_lower(_ value: CompletionItem) -> RustBuffer {
    return FfiConverterTypeCompletionItem.lower(value)
}


/**
 * Detailed completion item with full documentation and sorting
 */
public struct DetailedCompletionItem {
    /**
     * Display label
     */
    public var label: String
    /**
     * Completion kind for icon selection
     */
    public var kind: CompletionKind
    /**
     * Short detail text (type/module info)
     */
    public var detail: String?
    /**
     * Full documentation (markdown)
     */
    public var documentation: String?
    /**
     * Text to insert (may differ from label)
     */
    public var insertText: String?
    /**
     * Filter text for fuzzy matching
     */
    public var filterText: String?
    /**
     * Sort priority (lower = higher priority)
     */
    public var sortPriority: UInt32
    /**
     * Signature for operators/functions
     */
    public var signature: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Display label
         */label: String, 
        /**
         * Completion kind for icon selection
         */kind: CompletionKind, 
        /**
         * Short detail text (type/module info)
         */detail: String?, 
        /**
         * Full documentation (markdown)
         */documentation: String?, 
        /**
         * Text to insert (may differ from label)
         */insertText: String?, 
        /**
         * Filter text for fuzzy matching
         */filterText: String?, 
        /**
         * Sort priority (lower = higher priority)
         */sortPriority: UInt32, 
        /**
         * Signature for operators/functions
         */signature: String?) {
        self.label = label
        self.kind = kind
        self.detail = detail
        self.documentation = documentation
        self.insertText = insertText
        self.filterText = filterText
        self.sortPriority = sortPriority
        self.signature = signature
    }
}



extension DetailedCompletionItem: Equatable, Hashable {
    public static func ==(lhs: DetailedCompletionItem, rhs: DetailedCompletionItem) -> Bool {
        if lhs.label != rhs.label {
            return false
        }
        if lhs.kind != rhs.kind {
            return false
        }
        if lhs.detail != rhs.detail {
            return false
        }
        if lhs.documentation != rhs.documentation {
            return false
        }
        if lhs.insertText != rhs.insertText {
            return false
        }
        if lhs.filterText != rhs.filterText {
            return false
        }
        if lhs.sortPriority != rhs.sortPriority {
            return false
        }
        if lhs.signature != rhs.signature {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(label)
        hasher.combine(kind)
        hasher.combine(detail)
        hasher.combine(documentation)
        hasher.combine(insertText)
        hasher.combine(filterText)
        hasher.combine(sortPriority)
        hasher.combine(signature)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDetailedCompletionItem: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DetailedCompletionItem {
        return
            try DetailedCompletionItem(
                label: FfiConverterString.read(from: &buf), 
                kind: FfiConverterTypeCompletionKind.read(from: &buf), 
                detail: FfiConverterOptionString.read(from: &buf), 
                documentation: FfiConverterOptionString.read(from: &buf), 
                insertText: FfiConverterOptionString.read(from: &buf), 
                filterText: FfiConverterOptionString.read(from: &buf), 
                sortPriority: FfiConverterUInt32.read(from: &buf), 
                signature: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: DetailedCompletionItem, into buf: inout [UInt8]) {
        FfiConverterString.write(value.label, into: &buf)
        FfiConverterTypeCompletionKind.write(value.kind, into: &buf)
        FfiConverterOptionString.write(value.detail, into: &buf)
        FfiConverterOptionString.write(value.documentation, into: &buf)
        FfiConverterOptionString.write(value.insertText, into: &buf)
        FfiConverterOptionString.write(value.filterText, into: &buf)
        FfiConverterUInt32.write(value.sortPriority, into: &buf)
        FfiConverterOptionString.write(value.signature, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDetailedCompletionItem_lift(_ buf: RustBuffer) throws -> DetailedCompletionItem {
    return try FfiConverterTypeDetailedCompletionItem.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDetailedCompletionItem_lower(_ value: DetailedCompletionItem) -> RustBuffer {
    return FfiConverterTypeDetailedCompletionItem.lower(value)
}


/**
 * A diagnostic message
 */
public struct Diagnostic {
    public var range: Range
    public var severity: DiagnosticSeverity
    public var message: String
    public var code: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(range: Range, severity: DiagnosticSeverity, message: String, code: String?) {
        self.range = range
        self.severity = severity
        self.message = message
        self.code = code
    }
}



extension Diagnostic: Equatable, Hashable {
    public static func ==(lhs: Diagnostic, rhs: Diagnostic) -> Bool {
        if lhs.range != rhs.range {
            return false
        }
        if lhs.severity != rhs.severity {
            return false
        }
        if lhs.message != rhs.message {
            return false
        }
        if lhs.code != rhs.code {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(range)
        hasher.combine(severity)
        hasher.combine(message)
        hasher.combine(code)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDiagnostic: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Diagnostic {
        return
            try Diagnostic(
                range: FfiConverterTypeRange.read(from: &buf), 
                severity: FfiConverterTypeDiagnosticSeverity.read(from: &buf), 
                message: FfiConverterString.read(from: &buf), 
                code: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: Diagnostic, into buf: inout [UInt8]) {
        FfiConverterTypeRange.write(value.range, into: &buf)
        FfiConverterTypeDiagnosticSeverity.write(value.severity, into: &buf)
        FfiConverterString.write(value.message, into: &buf)
        FfiConverterOptionString.write(value.code, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDiagnostic_lift(_ buf: RustBuffer) throws -> Diagnostic {
    return try FfiConverterTypeDiagnostic.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDiagnostic_lower(_ value: Diagnostic) -> RustBuffer {
    return FfiConverterTypeDiagnostic.lower(value)
}


/**
 * Edit information for incremental parsing
 */
public struct EditInfo {
    public var startByte: UInt32
    public var oldEndByte: UInt32
    public var newEndByte: UInt32
    public var startPosition: Position
    public var oldEndPosition: Position
    public var newEndPosition: Position

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(startByte: UInt32, oldEndByte: UInt32, newEndByte: UInt32, startPosition: Position, oldEndPosition: Position, newEndPosition: Position) {
        self.startByte = startByte
        self.oldEndByte = oldEndByte
        self.newEndByte = newEndByte
        self.startPosition = startPosition
        self.oldEndPosition = oldEndPosition
        self.newEndPosition = newEndPosition
    }
}



extension EditInfo: Equatable, Hashable {
    public static func ==(lhs: EditInfo, rhs: EditInfo) -> Bool {
        if lhs.startByte != rhs.startByte {
            return false
        }
        if lhs.oldEndByte != rhs.oldEndByte {
            return false
        }
        if lhs.newEndByte != rhs.newEndByte {
            return false
        }
        if lhs.startPosition != rhs.startPosition {
            return false
        }
        if lhs.oldEndPosition != rhs.oldEndPosition {
            return false
        }
        if lhs.newEndPosition != rhs.newEndPosition {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(startByte)
        hasher.combine(oldEndByte)
        hasher.combine(newEndByte)
        hasher.combine(startPosition)
        hasher.combine(oldEndPosition)
        hasher.combine(newEndPosition)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEditInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EditInfo {
        return
            try EditInfo(
                startByte: FfiConverterUInt32.read(from: &buf), 
                oldEndByte: FfiConverterUInt32.read(from: &buf), 
                newEndByte: FfiConverterUInt32.read(from: &buf), 
                startPosition: FfiConverterTypePosition.read(from: &buf), 
                oldEndPosition: FfiConverterTypePosition.read(from: &buf), 
                newEndPosition: FfiConverterTypePosition.read(from: &buf)
        )
    }

    public static func write(_ value: EditInfo, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.startByte, into: &buf)
        FfiConverterUInt32.write(value.oldEndByte, into: &buf)
        FfiConverterUInt32.write(value.newEndByte, into: &buf)
        FfiConverterTypePosition.write(value.startPosition, into: &buf)
        FfiConverterTypePosition.write(value.oldEndPosition, into: &buf)
        FfiConverterTypePosition.write(value.newEndPosition, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEditInfo_lift(_ buf: RustBuffer) throws -> EditInfo {
    return try FfiConverterTypeEditInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEditInfo_lower(_ value: EditInfo) -> RustBuffer {
    return FfiConverterTypeEditInfo.lower(value)
}


/**
 * Syntax highlight token
 */
public struct HighlightToken {
    public var range: Range
    public var tokenType: String
    public var modifiers: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(range: Range, tokenType: String, modifiers: [String]) {
        self.range = range
        self.tokenType = tokenType
        self.modifiers = modifiers
    }
}



extension HighlightToken: Equatable, Hashable {
    public static func ==(lhs: HighlightToken, rhs: HighlightToken) -> Bool {
        if lhs.range != rhs.range {
            return false
        }
        if lhs.tokenType != rhs.tokenType {
            return false
        }
        if lhs.modifiers != rhs.modifiers {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(range)
        hasher.combine(tokenType)
        hasher.combine(modifiers)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHighlightToken: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HighlightToken {
        return
            try HighlightToken(
                range: FfiConverterTypeRange.read(from: &buf), 
                tokenType: FfiConverterString.read(from: &buf), 
                modifiers: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: HighlightToken, into buf: inout [UInt8]) {
        FfiConverterTypeRange.write(value.range, into: &buf)
        FfiConverterString.write(value.tokenType, into: &buf)
        FfiConverterSequenceString.write(value.modifiers, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHighlightToken_lift(_ buf: RustBuffer) throws -> HighlightToken {
    return try FfiConverterTypeHighlightToken.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHighlightToken_lower(_ value: HighlightToken) -> RustBuffer {
    return FfiConverterTypeHighlightToken.lower(value)
}


/**
 * Information about a single parameter
 */
public struct ParameterInfo {
    /**
     * Parameter name
     */
    public var label: String
    /**
     * Parameter documentation
     */
    public var documentation: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Parameter name
         */label: String, 
        /**
         * Parameter documentation
         */documentation: String?) {
        self.label = label
        self.documentation = documentation
    }
}



extension ParameterInfo: Equatable, Hashable {
    public static func ==(lhs: ParameterInfo, rhs: ParameterInfo) -> Bool {
        if lhs.label != rhs.label {
            return false
        }
        if lhs.documentation != rhs.documentation {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(label)
        hasher.combine(documentation)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeParameterInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ParameterInfo {
        return
            try ParameterInfo(
                label: FfiConverterString.read(from: &buf), 
                documentation: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: ParameterInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.label, into: &buf)
        FfiConverterOptionString.write(value.documentation, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeParameterInfo_lift(_ buf: RustBuffer) throws -> ParameterInfo {
    return try FfiConverterTypeParameterInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeParameterInfo_lower(_ value: ParameterInfo) -> RustBuffer {
    return FfiConverterTypeParameterInfo.lower(value)
}


/**
 * Position in a document (0-indexed)
 */
public struct Position {
    public var line: UInt32
    public var column: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(line: UInt32, column: UInt32) {
        self.line = line
        self.column = column
    }
}



extension Position: Equatable, Hashable {
    public static func ==(lhs: Position, rhs: Position) -> Bool {
        if lhs.line != rhs.line {
            return false
        }
        if lhs.column != rhs.column {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(line)
        hasher.combine(column)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePosition: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Position {
        return
            try Position(
                line: FfiConverterUInt32.read(from: &buf), 
                column: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: Position, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.line, into: &buf)
        FfiConverterUInt32.write(value.column, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePosition_lift(_ buf: RustBuffer) throws -> Position {
    return try FfiConverterTypePosition.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePosition_lower(_ value: Position) -> RustBuffer {
    return FfiConverterTypePosition.lower(value)
}


/**
 * Range in a document
 */
public struct Range {
    public var start: Position
    public var end: Position

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(start: Position, end: Position) {
        self.start = start
        self.end = end
    }
}



extension Range: Equatable, Hashable {
    public static func ==(lhs: Range, rhs: Range) -> Bool {
        if lhs.start != rhs.start {
            return false
        }
        if lhs.end != rhs.end {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(start)
        hasher.combine(end)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRange: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Range {
        return
            try Range(
                start: FfiConverterTypePosition.read(from: &buf), 
                end: FfiConverterTypePosition.read(from: &buf)
        )
    }

    public static func write(_ value: Range, into buf: inout [UInt8]) {
        FfiConverterTypePosition.write(value.start, into: &buf)
        FfiConverterTypePosition.write(value.end, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRange_lift(_ buf: RustBuffer) throws -> Range {
    return try FfiConverterTypeRange.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRange_lower(_ value: Range) -> RustBuffer {
    return FfiConverterTypeRange.lower(value)
}


/**
 * Signature help information for operator calls
 */
public struct SignatureHelp {
    /**
     * Available signatures (usually one)
     */
    public var signatures: [SignatureInfo]
    /**
     * Index of active signature
     */
    public var activeSignature: UInt32
    /**
     * Index of active parameter (for highlighting)
     */
    public var activeParameter: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Available signatures (usually one)
         */signatures: [SignatureInfo], 
        /**
         * Index of active signature
         */activeSignature: UInt32, 
        /**
         * Index of active parameter (for highlighting)
         */activeParameter: UInt32) {
        self.signatures = signatures
        self.activeSignature = activeSignature
        self.activeParameter = activeParameter
    }
}



extension SignatureHelp: Equatable, Hashable {
    public static func ==(lhs: SignatureHelp, rhs: SignatureHelp) -> Bool {
        if lhs.signatures != rhs.signatures {
            return false
        }
        if lhs.activeSignature != rhs.activeSignature {
            return false
        }
        if lhs.activeParameter != rhs.activeParameter {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(signatures)
        hasher.combine(activeSignature)
        hasher.combine(activeParameter)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSignatureHelp: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SignatureHelp {
        return
            try SignatureHelp(
                signatures: FfiConverterSequenceTypeSignatureInfo.read(from: &buf), 
                activeSignature: FfiConverterUInt32.read(from: &buf), 
                activeParameter: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: SignatureHelp, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeSignatureInfo.write(value.signatures, into: &buf)
        FfiConverterUInt32.write(value.activeSignature, into: &buf)
        FfiConverterUInt32.write(value.activeParameter, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSignatureHelp_lift(_ buf: RustBuffer) throws -> SignatureHelp {
    return try FfiConverterTypeSignatureHelp.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSignatureHelp_lower(_ value: SignatureHelp) -> RustBuffer {
    return FfiConverterTypeSignatureHelp.lower(value)
}


/**
 * Information about a single signature
 */
public struct SignatureInfo {
    /**
     * Full signature label (e.g., "Append(seq, elem)")
     */
    public var label: String
    /**
     * Documentation for this signature
     */
    public var documentation: String?
    /**
     * Parameters
     */
    public var parameters: [ParameterInfo]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Full signature label (e.g., "Append(seq, elem)")
         */label: String, 
        /**
         * Documentation for this signature
         */documentation: String?, 
        /**
         * Parameters
         */parameters: [ParameterInfo]) {
        self.label = label
        self.documentation = documentation
        self.parameters = parameters
    }
}



extension SignatureInfo: Equatable, Hashable {
    public static func ==(lhs: SignatureInfo, rhs: SignatureInfo) -> Bool {
        if lhs.label != rhs.label {
            return false
        }
        if lhs.documentation != rhs.documentation {
            return false
        }
        if lhs.parameters != rhs.parameters {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(label)
        hasher.combine(documentation)
        hasher.combine(parameters)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSignatureInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SignatureInfo {
        return
            try SignatureInfo(
                label: FfiConverterString.read(from: &buf), 
                documentation: FfiConverterOptionString.read(from: &buf), 
                parameters: FfiConverterSequenceTypeParameterInfo.read(from: &buf)
        )
    }

    public static func write(_ value: SignatureInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.label, into: &buf)
        FfiConverterOptionString.write(value.documentation, into: &buf)
        FfiConverterSequenceTypeParameterInfo.write(value.parameters, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSignatureInfo_lift(_ buf: RustBuffer) throws -> SignatureInfo {
    return try FfiConverterTypeSignatureInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSignatureInfo_lower(_ value: SignatureInfo) -> RustBuffer {
    return FfiConverterTypeSignatureInfo.lower(value)
}


/**
 * A symbol in the document
 */
public struct Symbol {
    public var name: String
    public var kind: SymbolKind
    public var range: Range
    public var selectionRange: Range?
    public var children: [Symbol]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, kind: SymbolKind, range: Range, selectionRange: Range?, children: [Symbol]) {
        self.name = name
        self.kind = kind
        self.range = range
        self.selectionRange = selectionRange
        self.children = children
    }
}



extension Symbol: Equatable, Hashable {
    public static func ==(lhs: Symbol, rhs: Symbol) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.kind != rhs.kind {
            return false
        }
        if lhs.range != rhs.range {
            return false
        }
        if lhs.selectionRange != rhs.selectionRange {
            return false
        }
        if lhs.children != rhs.children {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(kind)
        hasher.combine(range)
        hasher.combine(selectionRange)
        hasher.combine(children)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSymbol: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Symbol {
        return
            try Symbol(
                name: FfiConverterString.read(from: &buf), 
                kind: FfiConverterTypeSymbolKind.read(from: &buf), 
                range: FfiConverterTypeRange.read(from: &buf), 
                selectionRange: FfiConverterOptionTypeRange.read(from: &buf), 
                children: FfiConverterSequenceTypeSymbol.read(from: &buf)
        )
    }

    public static func write(_ value: Symbol, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterTypeSymbolKind.write(value.kind, into: &buf)
        FfiConverterTypeRange.write(value.range, into: &buf)
        FfiConverterOptionTypeRange.write(value.selectionRange, into: &buf)
        FfiConverterSequenceTypeSymbol.write(value.children, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSymbol_lift(_ buf: RustBuffer) throws -> Symbol {
    return try FfiConverterTypeSymbol.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSymbol_lower(_ value: Symbol) -> RustBuffer {
    return FfiConverterTypeSymbol.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Context where the cursor is located in the AST
 */

public enum CompletionContext {
    
    /**
     * At top level of module (can define operators, theorems, etc.)
     */
    case topLevel
    /**
     * After EXTENDS keyword (suggest module names)
     */
    case afterExtends
    /**
     * After INSTANCE keyword (suggest module names)
     */
    case afterInstance
    /**
     * Inside an expression (suggest variables, operators, constants)
     */
    case inExpression
    /**
     * Inside a PROOF block (suggest proof tactics)
     */
    case inProof
    /**
     * After \in or \subseteq (suggest set expressions)
     */
    case afterSetOperator
    /**
     * Inside LET binding definition area
     */
    case inLetDef
    /**
     * After WITH in INSTANCE (suggest parameter mappings)
     */
    case afterWith
    /**
     * Unknown context
     */
    case unknown
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCompletionContext: FfiConverterRustBuffer {
    typealias SwiftType = CompletionContext

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CompletionContext {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .topLevel
        
        case 2: return .afterExtends
        
        case 3: return .afterInstance
        
        case 4: return .inExpression
        
        case 5: return .inProof
        
        case 6: return .afterSetOperator
        
        case 7: return .inLetDef
        
        case 8: return .afterWith
        
        case 9: return .unknown
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CompletionContext, into buf: inout [UInt8]) {
        switch value {
        
        
        case .topLevel:
            writeInt(&buf, Int32(1))
        
        
        case .afterExtends:
            writeInt(&buf, Int32(2))
        
        
        case .afterInstance:
            writeInt(&buf, Int32(3))
        
        
        case .inExpression:
            writeInt(&buf, Int32(4))
        
        
        case .inProof:
            writeInt(&buf, Int32(5))
        
        
        case .afterSetOperator:
            writeInt(&buf, Int32(6))
        
        
        case .inLetDef:
            writeInt(&buf, Int32(7))
        
        
        case .afterWith:
            writeInt(&buf, Int32(8))
        
        
        case .unknown:
            writeInt(&buf, Int32(9))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompletionContext_lift(_ buf: RustBuffer) throws -> CompletionContext {
    return try FfiConverterTypeCompletionContext.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompletionContext_lower(_ value: CompletionContext) -> RustBuffer {
    return FfiConverterTypeCompletionContext.lower(value)
}



extension CompletionContext: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Completion item kind
 */

public enum CompletionKind {
    
    case keyword
    case `operator`
    case variable
    case constant
    case module
    case snippet
    case function
    case theorem
    case proofTactic
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCompletionKind: FfiConverterRustBuffer {
    typealias SwiftType = CompletionKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CompletionKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .keyword
        
        case 2: return .`operator`
        
        case 3: return .variable
        
        case 4: return .constant
        
        case 5: return .module
        
        case 6: return .snippet
        
        case 7: return .function
        
        case 8: return .theorem
        
        case 9: return .proofTactic
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CompletionKind, into buf: inout [UInt8]) {
        switch value {
        
        
        case .keyword:
            writeInt(&buf, Int32(1))
        
        
        case .`operator`:
            writeInt(&buf, Int32(2))
        
        
        case .variable:
            writeInt(&buf, Int32(3))
        
        
        case .constant:
            writeInt(&buf, Int32(4))
        
        
        case .module:
            writeInt(&buf, Int32(5))
        
        
        case .snippet:
            writeInt(&buf, Int32(6))
        
        
        case .function:
            writeInt(&buf, Int32(7))
        
        
        case .theorem:
            writeInt(&buf, Int32(8))
        
        
        case .proofTactic:
            writeInt(&buf, Int32(9))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompletionKind_lift(_ buf: RustBuffer) throws -> CompletionKind {
    return try FfiConverterTypeCompletionKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompletionKind_lower(_ value: CompletionKind) -> RustBuffer {
    return FfiConverterTypeCompletionKind.lower(value)
}



extension CompletionKind: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Diagnostic severity
 */

public enum DiagnosticSeverity {
    
    case error
    case warning
    case information
    case hint
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDiagnosticSeverity: FfiConverterRustBuffer {
    typealias SwiftType = DiagnosticSeverity

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DiagnosticSeverity {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .error
        
        case 2: return .warning
        
        case 3: return .information
        
        case 4: return .hint
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DiagnosticSeverity, into buf: inout [UInt8]) {
        switch value {
        
        
        case .error:
            writeInt(&buf, Int32(1))
        
        
        case .warning:
            writeInt(&buf, Int32(2))
        
        
        case .information:
            writeInt(&buf, Int32(3))
        
        
        case .hint:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDiagnosticSeverity_lift(_ buf: RustBuffer) throws -> DiagnosticSeverity {
    return try FfiConverterTypeDiagnosticSeverity.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDiagnosticSeverity_lower(_ value: DiagnosticSeverity) -> RustBuffer {
    return FfiConverterTypeDiagnosticSeverity.lower(value)
}



extension DiagnosticSeverity: Equatable, Hashable {}




public enum ParseError {

    
    
    case ParseFailed(message: String
    )
    case InvalidEncoding
    case Internal(message: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeParseError: FfiConverterRustBuffer {
    typealias SwiftType = ParseError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ParseError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .ParseFailed(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .InvalidEncoding
        case 3: return .Internal(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ParseError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .ParseFailed(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case .InvalidEncoding:
            writeInt(&buf, Int32(2))
        
        
        case let .Internal(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


extension ParseError: Equatable, Hashable {}

extension ParseError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Symbol kinds in TLA+
 */

public enum SymbolKind {
    
    case module
    case `operator`
    case variable
    case constant
    case theorem
    case definition
    case instance
    case assumption
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSymbolKind: FfiConverterRustBuffer {
    typealias SwiftType = SymbolKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SymbolKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .module
        
        case 2: return .`operator`
        
        case 3: return .variable
        
        case 4: return .constant
        
        case 5: return .theorem
        
        case 6: return .definition
        
        case 7: return .instance
        
        case 8: return .assumption
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SymbolKind, into buf: inout [UInt8]) {
        switch value {
        
        
        case .module:
            writeInt(&buf, Int32(1))
        
        
        case .`operator`:
            writeInt(&buf, Int32(2))
        
        
        case .variable:
            writeInt(&buf, Int32(3))
        
        
        case .constant:
            writeInt(&buf, Int32(4))
        
        
        case .theorem:
            writeInt(&buf, Int32(5))
        
        
        case .definition:
            writeInt(&buf, Int32(6))
        
        
        case .instance:
            writeInt(&buf, Int32(7))
        
        
        case .assumption:
            writeInt(&buf, Int32(8))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSymbolKind_lift(_ buf: RustBuffer) throws -> SymbolKind {
    return try FfiConverterTypeSymbolKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSymbolKind_lower(_ value: SymbolKind) -> RustBuffer {
    return FfiConverterTypeSymbolKind.lower(value)
}



extension SymbolKind: Equatable, Hashable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeRange: FfiConverterRustBuffer {
    typealias SwiftType = Range?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeRange.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeRange.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeSignatureHelp: FfiConverterRustBuffer {
    typealias SwiftType = SignatureHelp?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeSignatureHelp.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeSignatureHelp.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeCompletionItem: FfiConverterRustBuffer {
    typealias SwiftType = [CompletionItem]

    public static func write(_ value: [CompletionItem], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeCompletionItem.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [CompletionItem] {
        let len: Int32 = try readInt(&buf)
        var seq = [CompletionItem]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeCompletionItem.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDetailedCompletionItem: FfiConverterRustBuffer {
    typealias SwiftType = [DetailedCompletionItem]

    public static func write(_ value: [DetailedCompletionItem], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDetailedCompletionItem.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [DetailedCompletionItem] {
        let len: Int32 = try readInt(&buf)
        var seq = [DetailedCompletionItem]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDetailedCompletionItem.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDiagnostic: FfiConverterRustBuffer {
    typealias SwiftType = [Diagnostic]

    public static func write(_ value: [Diagnostic], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDiagnostic.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Diagnostic] {
        let len: Int32 = try readInt(&buf)
        var seq = [Diagnostic]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDiagnostic.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeHighlightToken: FfiConverterRustBuffer {
    typealias SwiftType = [HighlightToken]

    public static func write(_ value: [HighlightToken], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeHighlightToken.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [HighlightToken] {
        let len: Int32 = try readInt(&buf)
        var seq = [HighlightToken]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeHighlightToken.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeParameterInfo: FfiConverterRustBuffer {
    typealias SwiftType = [ParameterInfo]

    public static func write(_ value: [ParameterInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeParameterInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ParameterInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [ParameterInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeParameterInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSignatureInfo: FfiConverterRustBuffer {
    typealias SwiftType = [SignatureInfo]

    public static func write(_ value: [SignatureInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSignatureInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SignatureInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [SignatureInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSignatureInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSymbol: FfiConverterRustBuffer {
    typealias SwiftType = [Symbol]

    public static func write(_ value: [Symbol], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSymbol.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Symbol] {
        let len: Int32 = try readInt(&buf)
        var seq = [Symbol]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSymbol.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_tla_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_tla_core_checksum_method_parseresult_get_diagnostics() != 64679) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tla_core_checksum_method_parseresult_is_valid() != 45096) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tla_core_checksum_method_tlacore_analyze_context() != 45035) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tla_core_checksum_method_tlacore_get_completions() != 1608) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tla_core_checksum_method_tlacore_get_detailed_completions() != 50767) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tla_core_checksum_method_tlacore_get_highlights() != 36699) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tla_core_checksum_method_tlacore_get_signature_help() != 22666) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tla_core_checksum_method_tlacore_get_symbols() != 15760) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tla_core_checksum_method_tlacore_parse() != 2082) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tla_core_checksum_method_tlacore_parse_incremental() != 65059) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tla_core_checksum_constructor_tlacore_new() != 24068) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all