import XCTest
@testable import TLAStudioApp

// MARK: - TLC Config Tests

final class TLCConfigTests: XCTestCase {

    // MARK: - Default Values Tests

    func testDefaultModelConfig() {
        let config = ModelConfig(
            specFile: URL(fileURLWithPath: "/tmp/test.tla")
        )

        XCTAssertEqual(config.name, "Default")
        XCTAssertEqual(config.initPredicate, "Init")
        XCTAssertEqual(config.nextAction, "Next")
        XCTAssertTrue(config.constants.isEmpty)
        XCTAssertTrue(config.invariants.isEmpty)
        XCTAssertTrue(config.temporalProperties.isEmpty)
        XCTAssertNil(config.stateConstraint)
        XCTAssertNil(config.actionConstraint)
        XCTAssertEqual(config.workers, 4)
        XCTAssertTrue(config.checkDeadlock)
        XCTAssertFalse(config.depthFirst)
        XCTAssertNil(config.maxDepth)
        XCTAssertTrue(config.checkpointEnabled)
        XCTAssertEqual(config.checkpointInterval, 300)
    }

    // MARK: - Config File Generation Tests

    func testConfigFileGenerationBasic() {
        let config = ModelConfig(
            specFile: URL(fileURLWithPath: "/tmp/test.tla"),
            initPredicate: "Init",
            nextAction: "Next"
        )

        let content = config.generateConfigFile()

        XCTAssertTrue(content.contains("INIT Init"))
        XCTAssertTrue(content.contains("NEXT Next"))
        XCTAssertTrue(content.contains("Generated by TLA+ Studio"))
    }

    func testConfigFileGenerationWithCustomInitNext() {
        let config = ModelConfig(
            specFile: URL(fileURLWithPath: "/tmp/test.tla"),
            initPredicate: "MyInit",
            nextAction: "MyNext"
        )

        let content = config.generateConfigFile()

        XCTAssertTrue(content.contains("INIT MyInit"))
        XCTAssertTrue(content.contains("NEXT MyNext"))
    }

    func testConfigFileGenerationWithSpecificationPreservesSpecificationForm() {
        let config = ModelConfig(
            specFile: URL(fileURLWithPath: "/tmp/test.tla"),
            specification: "Spec",
            initPredicate: "Init",
            nextAction: "Next"
        )

        let content = config.generateConfigFile()

        XCTAssertTrue(content.contains("SPECIFICATION Spec"))
        XCTAssertFalse(content.contains("INIT Init"))
        XCTAssertFalse(content.contains("NEXT Next"))
    }

    func testParseConfigFilePreservesSpecificationDirective() {
        let parsed = ModelConfig.parse(content: """
        \\* Generated by TLA+ Studio
        SPECIFICATION Spec
        CONSTANT N = 3
        INVARIANT TypeOK
        """)

        XCTAssertEqual(parsed.specification, "Spec")
        XCTAssertEqual(parsed.constants["N"], .int(3))
        XCTAssertEqual(parsed.invariants, ["TypeOK"])
    }

    func testConfigFileGenerationWithConstants() {
        let config = ModelConfig(
            specFile: URL(fileURLWithPath: "/tmp/test.tla"),
            constants: [
                "N": .int(3),
                "Flag": .bool(true),
                "Name": .string("test")
            ]
        )

        let content = config.generateConfigFile()

        XCTAssertTrue(content.contains("CONSTANT N = 3"))
        XCTAssertTrue(content.contains("CONSTANT Flag = TRUE"))
        XCTAssertTrue(content.contains("CONSTANT Name = \"test\""))
    }

    func testConfigFileGenerationWithInvariants() {
        let config = ModelConfig(
            specFile: URL(fileURLWithPath: "/tmp/test.tla"),
            invariants: ["TypeOK", "Safety"]
        )

        let content = config.generateConfigFile()

        XCTAssertTrue(content.contains("INVARIANT TypeOK"))
        XCTAssertTrue(content.contains("INVARIANT Safety"))
    }

    func testConfigFileGenerationWithProperties() {
        let config = ModelConfig(
            specFile: URL(fileURLWithPath: "/tmp/test.tla"),
            temporalProperties: ["Liveness", "Fairness"]
        )

        let content = config.generateConfigFile()

        XCTAssertTrue(content.contains("PROPERTY Liveness"))
        XCTAssertTrue(content.contains("PROPERTY Fairness"))
    }

    func testConfigFileGenerationWithStateConstraint() {
        let config = ModelConfig(
            specFile: URL(fileURLWithPath: "/tmp/test.tla"),
            stateConstraint: "x < 10"
        )

        let content = config.generateConfigFile()

        XCTAssertTrue(content.contains("CONSTRAINT x < 10"))
    }

    func testConfigFileGenerationWithActionConstraint() {
        let config = ModelConfig(
            specFile: URL(fileURLWithPath: "/tmp/test.tla"),
            actionConstraint: "x' > x"
        )

        let content = config.generateConfigFile()

        XCTAssertTrue(content.contains("ACTION_CONSTRAINT x' > x"))
    }

    func testConfigFileGenerationWithSymmetry() {
        let config = ModelConfig(
            specFile: URL(fileURLWithPath: "/tmp/test.tla"),
            symmetrySets: ["Procs": ["p1", "p2", "p3"]]
        )

        let content = config.generateConfigFile()

        XCTAssertTrue(content.contains("SYMMETRY Procs"))
    }

    func testConfigFileGenerationEmptyConstraintsOmitted() {
        let config = ModelConfig(
            specFile: URL(fileURLWithPath: "/tmp/test.tla"),
            stateConstraint: "",  // Empty should be omitted
            actionConstraint: ""
        )

        let content = config.generateConfigFile()

        XCTAssertFalse(content.contains("CONSTRAINT"))
        XCTAssertFalse(content.contains("ACTION_CONSTRAINT"))
    }

    func testConfigFileGenerationEmptyInvariantsOmitted() {
        let config = ModelConfig(
            specFile: URL(fileURLWithPath: "/tmp/test.tla"),
            invariants: ["TypeOK", "", "Safety"]  // Empty should be filtered
        )

        let content = config.generateConfigFile()

        XCTAssertTrue(content.contains("INVARIANT TypeOK"))
        XCTAssertTrue(content.contains("INVARIANT Safety"))
        // Count INVARIANT occurrences - should be exactly 2
        let count = content.components(separatedBy: "INVARIANT").count - 1
        XCTAssertEqual(count, 2)
    }

    // MARK: - Constant Value Formatting Tests

    func testConstantValueIntFormat() {
        let value = ConstantValue.int(42)
        XCTAssertEqual(value.tlcFormat, "42")
    }

    func testConstantValueNegativeIntFormat() {
        let value = ConstantValue.int(-10)
        XCTAssertEqual(value.tlcFormat, "-10")
    }

    func testConstantValueBoolTrueFormat() {
        let value = ConstantValue.bool(true)
        XCTAssertEqual(value.tlcFormat, "TRUE")
    }

    func testConstantValueBoolFalseFormat() {
        let value = ConstantValue.bool(false)
        XCTAssertEqual(value.tlcFormat, "FALSE")
    }

    func testConstantValueStringFormat() {
        let value = ConstantValue.string("hello")
        XCTAssertEqual(value.tlcFormat, "\"hello\"")
    }

    func testConstantValueEmptySetFormat() {
        let value = ConstantValue.set([])
        XCTAssertEqual(value.tlcFormat, "{}")
    }

    func testConstantValueSetFormat() {
        let value = ConstantValue.set([.int(1), .int(2), .int(3)])
        XCTAssertEqual(value.tlcFormat, "{1, 2, 3}")
    }

    func testConstantValueModelValueFormat() {
        let value = ConstantValue.modelValue("mv1")
        XCTAssertEqual(value.tlcFormat, "mv1")
    }

    func testConstantValueSymmetrySetFormat() {
        let value = ConstantValue.symmetrySet("Procs")
        XCTAssertEqual(value.tlcFormat, "Procs")
    }

    // MARK: - Constant Value Codable Tests

    func testConstantValueIntCodable() throws {
        let original = ConstantValue.int(42)
        let encoded = try JSONEncoder().encode(original)
        let decoded = try JSONDecoder().decode(ConstantValue.self, from: encoded)
        XCTAssertEqual(original, decoded)
    }

    func testConstantValueStringCodable() throws {
        let original = ConstantValue.string("test")
        let encoded = try JSONEncoder().encode(original)
        let decoded = try JSONDecoder().decode(ConstantValue.self, from: encoded)
        XCTAssertEqual(original, decoded)
    }

    func testConstantValueBoolCodable() throws {
        let original = ConstantValue.bool(true)
        let encoded = try JSONEncoder().encode(original)
        let decoded = try JSONDecoder().decode(ConstantValue.self, from: encoded)
        XCTAssertEqual(original, decoded)
    }

    func testConstantValueSetCodable() throws {
        let original = ConstantValue.set([.int(1), .int(2)])
        let encoded = try JSONEncoder().encode(original)
        let decoded = try JSONDecoder().decode(ConstantValue.self, from: encoded)
        XCTAssertEqual(original, decoded)
    }

    func testConstantValueModelValueCodable() throws {
        let original = ConstantValue.modelValue("mv1")
        let encoded = try JSONEncoder().encode(original)
        let decoded = try JSONDecoder().decode(ConstantValue.self, from: encoded)
        XCTAssertEqual(original, decoded)
    }

    func testConstantValueSymmetrySetCodable() throws {
        let original = ConstantValue.symmetrySet("Procs")
        let encoded = try JSONEncoder().encode(original)
        let decoded = try JSONDecoder().decode(ConstantValue.self, from: encoded)
        XCTAssertEqual(original, decoded)
    }

    // MARK: - ModelConfig Codable Tests

    func testModelConfigCodable() throws {
        let original = ModelConfig(
            name: "TestConfig",
            specFile: URL(fileURLWithPath: "/tmp/test.tla"),
            initPredicate: "MyInit",
            nextAction: "MyNext",
            constants: ["N": .int(3)],
            invariants: ["TypeOK"],
            workers: 8
        )

        let encoded = try JSONEncoder().encode(original)
        let decoded = try JSONDecoder().decode(ModelConfig.self, from: encoded)

        XCTAssertEqual(original.name, decoded.name)
        XCTAssertEqual(original.initPredicate, decoded.initPredicate)
        XCTAssertEqual(original.nextAction, decoded.nextAction)
        XCTAssertEqual(original.constants, decoded.constants)
        XCTAssertEqual(original.invariants, decoded.invariants)
        XCTAssertEqual(original.workers, decoded.workers)
    }

    // MARK: - Temp Config File Tests

    func testWriteTempConfigFile() throws {
        let config = ModelConfig(
            specFile: URL(fileURLWithPath: "/tmp/test.tla"),
            invariants: ["TypeOK"]
        )

        let url = try config.writeTempConfigFile()

        // Verify file exists
        XCTAssertTrue(FileManager.default.fileExists(atPath: url.path))

        // Verify content
        let content = try String(contentsOf: url, encoding: .utf8)
        XCTAssertTrue(content.contains("INVARIANT TypeOK"))

        // Clean up
        try? FileManager.default.removeItem(at: url)
    }

    // MARK: - ModelCheckProgress Tests

    func testModelCheckProgressPhases() {
        // Test all phase values
        let phases: [ModelCheckProgress.Phase] = [.parsing, .computing, .checkingLiveness, .done, .error]

        for phase in phases {
            let progress = ModelCheckProgress(sessionId: UUID(), phase: phase)
            XCTAssertEqual(progress.phase, phase)
        }
    }

    func testModelCheckProgressCodable() throws {
        let original = ModelCheckProgress(
            sessionId: UUID(),
            phase: .computing,
            statesFound: 1000,
            distinctStates: 500,
            statesLeft: 250,
            duration: 10.5,
            statesPerSecond: 100.0,
            currentAction: "Next",
            coverage: [ActionCoverage(actionName: "Init", count: 1, distinctStates: 1)],
            memoryUsed: 1024
        )

        let encoded = try JSONEncoder().encode(original)
        let decoded = try JSONDecoder().decode(ModelCheckProgress.self, from: encoded)

        XCTAssertEqual(original.sessionId, decoded.sessionId)
        XCTAssertEqual(original.phase, decoded.phase)
        XCTAssertEqual(original.statesFound, decoded.statesFound)
        XCTAssertEqual(original.distinctStates, decoded.distinctStates)
        XCTAssertEqual(original.statesPerSecond, decoded.statesPerSecond)
    }

    // MARK: - ActionCoverage Tests

    func testActionCoverageId() {
        let coverage = ActionCoverage(actionName: "Next", count: 100, distinctStates: 50)
        XCTAssertEqual(coverage.id, "Next")
    }

    func testActionCoverageCodable() throws {
        let original = ActionCoverage(actionName: "Next", count: 100, distinctStates: 50)
        let encoded = try JSONEncoder().encode(original)
        let decoded = try JSONDecoder().decode(ActionCoverage.self, from: encoded)

        XCTAssertEqual(original.actionName, decoded.actionName)
        XCTAssertEqual(original.count, decoded.count)
        XCTAssertEqual(original.distinctStates, decoded.distinctStates)
    }

    // MARK: - ModelCheckResult Tests

    func testModelCheckResultHasErrorTrace() {
        let resultWithTrace = ModelCheckResult(
            sessionId: UUID(),
            success: false,
            statesFound: 100,
            distinctStates: 50,
            duration: 1.0,
            coverage: [],
            errorTrace: ErrorTrace(type: .invariantViolation, message: "Test"),
            message: "Error"
        )

        XCTAssertTrue(resultWithTrace.hasErrorTrace)

        let resultWithoutTrace = ModelCheckResult(
            sessionId: UUID(),
            success: true,
            statesFound: 100,
            distinctStates: 50,
            duration: 1.0,
            coverage: [],
            errorTrace: nil,
            message: nil
        )

        XCTAssertFalse(resultWithoutTrace.hasErrorTrace)
    }

    func testModelCheckResultErrorTraceStateCount() {
        let trace = ErrorTrace(
            type: .invariantViolation,
            message: "Test",
            states: [
                TraceState(id: 0),
                TraceState(id: 1),
                TraceState(id: 2)
            ]
        )

        let result = ModelCheckResult(
            sessionId: UUID(),
            success: false,
            statesFound: 100,
            distinctStates: 50,
            duration: 1.0,
            coverage: [],
            errorTrace: trace,
            message: "Error"
        )

        XCTAssertEqual(result.errorTraceStateCount, 3)
    }

    func testModelCheckResultNoErrorTraceStateCount() {
        let result = ModelCheckResult(
            sessionId: UUID(),
            success: true,
            statesFound: 100,
            distinctStates: 50,
            duration: 1.0,
            coverage: [],
            errorTrace: nil,
            message: nil
        )

        XCTAssertEqual(result.errorTraceStateCount, 0)
    }
}
