import Foundation
import os

// MARK: - Runner Abstraction

/// Seam for tests: `SimulationSession` talks to this protocol, the real
/// implementation shells out to TLC.
protocol SimulationExpanding: Sendable {
    func enumerateInitialStates(context: SimulationSpecContext) async -> Result<SimExpansion, SimulationError>
    func expand(_ state: SimState, context: SimulationSpecContext) async -> Result<SimExpansion, SimulationError>
    func evaluate(_ expression: String, in state: SimState, context: SimulationSpecContext) async -> Result<String, SimulationError>
}

// MARK: - Simulation Runner

/// Runs one short TLC process per interactive-simulation step (initial-state
/// enumeration, one-step expansion, or expression evaluation), using the
/// modules generated by `SimulationModuleBuilder`.
///
/// Prefers the bundled native TLC binaries (no JVM startup cost) and falls
/// back to `java -cp tla2tools.jar tlc2.TLC`. All subprocesses go through
/// `JavaProcessRunner.run` for bounded capture, timeout, and ProcessRegistry
/// reaping.
actor SimulationRunner: SimulationExpanding {

    static let shared = SimulationRunner()

    private let logger = Log.logger(category: "SimulationRunner")

    /// Wall-clock limit per TLC run. Interactive steps are expected to take
    /// well under a second; the headroom covers JVM startup and big fan-outs.
    private let runTimeout: TimeInterval = 60

    private enum Toolchain {
        case native(URL)
        case jvm(javaPath: String, jar: URL)
    }

    private func locateToolchain() -> Toolchain? {
        if let native = BinaryDiscovery.find(named: "tlc-native") {
            return .native(native)
        }
        if let native = BinaryDiscovery.find(named: "tlc-native-fast") {
            return .native(native)
        }
        if let jar = JavaProcessRunner.findTLA2Tools(),
           let java = JavaProcessRunner.findJava() {
            return .jvm(javaPath: java, jar: jar)
        }
        return nil
    }

    // MARK: - Public API

    func enumerateInitialStates(context: SimulationSpecContext) async -> Result<SimExpansion, SimulationError> {
        let module = SimulationModuleBuilder.initialStatesModule(context: context)
        let config = SimulationModuleBuilder.configFile(context: context, includeConstraint: true)

        let run: RunResult
        do {
            run = try await runTLC(module: module, config: config, searchPaths: context.searchPaths, wantDump: true)
        } catch {
            return .failure(asSimulationError(error))
        }

        let graph = SimulationDotParser.parse(dotText: run.dotText ?? "", actionLabels: [:])
        guard !graph.origins.isEmpty else {
            if let message = SimulationTLCErrorExtractor.extract(from: run.output) {
                return .failure(.tlcFailed(message))
            }
            return .failure(.noStates)
        }
        return .success(SimExpansion(origins: graph.origins, successors: [], truncated: graph.truncated))
    }

    func expand(_ state: SimState, context: SimulationSpecContext) async -> Result<SimExpansion, SimulationError> {
        let result = await expandOnce(state, context: context)

        // If the decomposed module failed (most likely a conservative-split
        // miss that broke parsing), retry once with Next treated as a single
        // action — generic labels, identical semantics. Genuine spec errors
        // reproduce in the fallback run and are reported from there.
        if case .failure(let error) = result, context.actions != nil {
            switch error {
            case .tlcFailed, .noStates:
                logger.notice("Decomposed expansion failed; retrying with single-action Next")
                let fallbackContext = SimulationSpecContext(
                    userModuleName: context.userModuleName,
                    searchPaths: context.searchPaths,
                    config: context.config,
                    actions: nil
                )
                return await expandOnce(state, context: fallbackContext)
            case .toolchainMissing, .invalidExpression, .cancelled:
                break
            }
        }
        return result
    }

    func evaluate(_ expression: String, in state: SimState, context: SimulationSpecContext) async -> Result<String, SimulationError> {
        let module: String
        do {
            module = try SimulationModuleBuilder.evaluationModule(
                context: context, state: state, expression: expression
            )
        } catch let error as SimulationError {
            return .failure(error)
        } catch {
            return .failure(.invalidExpression(error.localizedDescription))
        }
        let config = SimulationModuleBuilder.configFile(context: context, includeConstraint: false)

        let run: RunResult
        do {
            run = try await runTLC(module: module, config: config, searchPaths: context.searchPaths, wantDump: false)
        } catch {
            return .failure(asSimulationError(error))
        }
        return SimulationEvalParser.parse(output: run.output)
    }

    // MARK: - Internals

    private func expandOnce(_ state: SimState, context: SimulationSpecContext) async -> Result<SimExpansion, SimulationError> {
        let module = SimulationModuleBuilder.expansionModule(context: context, state: state)
        let config = SimulationModuleBuilder.configFile(context: context, includeConstraint: true)

        let run: RunResult
        do {
            run = try await runTLC(module: module, config: config, searchPaths: context.searchPaths, wantDump: true)
        } catch {
            return .failure(asSimulationError(error))
        }

        let graph = SimulationDotParser.parse(
            dotText: run.dotText ?? "",
            actionLabels: actionLabelMap(for: context)
        )
        guard !graph.origins.isEmpty else {
            if let message = SimulationTLCErrorExtractor.extract(from: run.output) {
                return .failure(.tlcFailed(message))
            }
            return .failure(.noStates)
        }
        return .success(SimExpansion(
            origins: graph.origins,
            successors: graph.successors,
            truncated: graph.truncated
        ))
    }

    private func actionLabelMap(for context: SimulationSpecContext) -> [String: String] {
        var map = [SimulationModuleBuilder.nextName: "Next"]
        if let actions = context.actions {
            for (index, action) in actions.enumerated() {
                map["\(SimulationModuleBuilder.actionNamePrefix)\(index + 1)"] = action.label
            }
        } else {
            map["\(SimulationModuleBuilder.actionNamePrefix)1"] = "Next"
        }
        return map
    }

    private struct RunResult {
        let output: String
        let dotText: String?
    }

    private func runTLC(
        module: String,
        config: String,
        searchPaths: [URL],
        wantDump: Bool
    ) async throws -> RunResult {
        guard let toolchain = locateToolchain() else {
            throw SimulationError.toolchainMissing
        }

        let workDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("TLAStudio-sim-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: workDir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: workDir) }

        let moduleName = SimulationModuleBuilder.moduleName
        try module.write(to: workDir.appendingPathComponent("\(moduleName).tla"), atomically: true, encoding: .utf8)
        try config.write(to: workDir.appendingPathComponent("\(moduleName).cfg"), atomically: true, encoding: .utf8)

        var tlcArguments = ["-deadlock", "-workers", "1", "-config", "\(moduleName).cfg"]
        if wantDump {
            tlcArguments.append(contentsOf: ["-dump", "dot,actionlabels", "dump"])
        }
        tlcArguments.append("\(moduleName).tla")

        let libraryProperty: String? = {
            let paths = searchPaths.map(\.path).filter { !$0.isEmpty }
            return paths.isEmpty ? nil : "-DTLA-Library=\(paths.joined(separator: ":"))"
        }()

        let executableURL: URL
        var arguments: [String] = []
        switch toolchain {
        case .native(let url):
            executableURL = url
            if let libraryProperty { arguments.append(libraryProperty) }
            arguments.append(contentsOf: tlcArguments)
        case .jvm(let javaPath, let jar):
            executableURL = URL(fileURLWithPath: javaPath)
            if let libraryProperty { arguments.append(libraryProperty) }
            // Small heap: simulation runs touch a handful of states.
            arguments.append(contentsOf: ["-Xmx2g", "-XX:+UseParallelGC", "-cp", jar.path, "tlc2.TLC"])
            arguments.append(contentsOf: tlcArguments)
        }

        let result = try await JavaProcessRunner.run(
            executableURL: executableURL,
            arguments: arguments,
            currentDirectoryURL: workDir,
            timeout: runTimeout
        )

        let output = (String(data: result.stdout, encoding: .utf8) ?? "")
            + "\n" + (String(data: result.stderr, encoding: .utf8) ?? "")

        var dotText: String?
        if wantDump {
            dotText = try? String(contentsOf: workDir.appendingPathComponent("dump.dot"), encoding: .utf8)
        }
        return RunResult(output: output, dotText: dotText)
    }

    private func asSimulationError(_ error: Error) -> SimulationError {
        if let simulationError = error as? SimulationError {
            return simulationError
        }
        return .tlcFailed(error.localizedDescription)
    }
}
